// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxpccybkdafnxitfvobx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54cGNjeWJrZGFmbnhpdGZ2b2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTg4NzksImV4cCI6MjA2OTkzNDg3OX0._bRhztTHhxkKY1lnhGr69-EomGpg2ltkiEiRVvoQyek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});